begin fibonacci:
    n : int <- read

    a : int <- 0
    b : int <- 1
    c : int <- 1
    i : int <- 2

    when (n!=0) repeat:
        is (n==1)?
            write n

        end
        otherwise:
            when (i<=n) repeat:
                c <- a + b
                a <- b
                b <- c
                i <- i + 1
            end
            write c

        end
    n <- read 
    end
end